# Generated by Django 4.2.13 on 2026-05-09 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChickenBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=150, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicken_batches', to='farms.farm')),
            ],
            options={
                'db_table': 'chicken_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChickenMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('quantity', models.IntegerField()),
                ('movement_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='chickens.chickenbatch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chicken_movements', to='farms.farm')),
            ],
            options={
                'db_table': 'chicken_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm_id', 'type'], name='idx_chicken_mov_farm_type'), models.Index(fields=['batch_id', 'type'], name='idx_chicken_mov_batch_type'), models.Index(fields=['movement_date'], name='idx_chicken_mov_date'), models.Index(fields=['farm_id', 'reason'], name='idx_chicken_mov_farm_reason')],
            },
        ),
    ]
