# Generated by Django 4.2.13 on 2026-05-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'provinces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserProvinceAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='provinces.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='province_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_province_access',
                'unique_together': {('user', 'province')},
            },
        ),
    ]
