# Generated by Django 4.2.13 on 2026-05-09 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provinces', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('location', models.TextField(blank=True, null=True)),
                ('capacity', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farms', to='provinces.province')),
            ],
            options={
                'db_table': 'farms',
                'ordering': ['name'],
                'unique_together': {('province', 'name')},
            },
        ),
        migrations.CreateModel(
            name='UserFarmAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='farms.farm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_farm_access',
                'unique_together': {('user', 'farm')},
            },
        ),
    ]
