# Generated by Django 4.2.13 on 2026-05-09 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('farmer', 'Farmer'), ('worker', 'Worker'), ('manager', 'Manager')], max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='farms.farm')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['-created_at'],
            },
        ),
    ]
