# Generated by Django 4.2.13 on 2026-05-09 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('kg', 'KG')], max_length=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='feed_inventory', to='farms.farm')),
            ],
            options={
                'db_table': 'feed_inventory',
            },
        ),
        migrations.CreateModel(
            name='FeedTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT')], max_length=3)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(choices=[('bag', 'Bag'), ('kg', 'KG')], max_length=5)),
                ('transaction_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feed_transactions', to='farms.farm')),
            ],
            options={
                'db_table': 'feed_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farm_id', 'type'], name='idx_feed_tx_farm_type'), models.Index(fields=['transaction_date'], name='idx_feed_tx_date')],
            },
        ),
    ]
